AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 30
    Runtime: java11
    MemorySize: 512
Resources:
  CrudApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: com.example.crudapi.handler.StreamLambdaHandler::handleRequest
      Runtime: java11
      Events:
        Api:
          Type: Api
          Properties:
            Path: /items
            Method: any
      Policies: AWSLambdaBasicExecutionRole
Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
